# Generated by Django 6.0.6 on 2026-09-02 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Sign in successful'), ('LOGIN_FAILED', 'Failed sign-in attempt'), ('PASSWORD_CHANGED', 'Password changed'), ('TWO_FACTOR_ENABLED', 'Two-factor authentication enabled'), ('TWO_FACTOR_DISABLED', 'Two-factor authentication disabled'), ('BACKUP_CODES_GENERATED', 'Recovery codes regenerated'), ('BACKUP_CODE_USED', 'Sign in using recovery code'), ('SESSION_REVOKED', 'Device session revoked'), ('ALL_SESSIONS_REVOKED', 'All other sessions signed out')], db_index=True, max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('device_type', models.CharField(default='Desktop', max_length=50)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
